config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :inventories
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  monetize :price_cents
  monetize :cost_cents
  monetize :sale_price_cents
  has_one :product, :foreign_key => :id, :primary_key => :product_id

  filterrific(
   default_filter_params: { sorted_by: 'product_id_asc' },
   available_filters: [
     :sorted_by,
     :search_query,
     :with_country_id,
     :with_created_at_gte
   ]
 )
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /inventories or /inventories.json
  def index
    @inventories = current_user.inventories.paginate(page: params[:page], per_page: 10).order(:product_name)
    @inventories = @inventories.where(:product_id => params['product_id_filter']) if params['product_id_filter'].present?
    @inventories = @inventories.where(:sku => params['sku_filter']) if params['sku_filter'].present?
    @inventories = @inventories.where('quantity <= ?', params['quantity_threshold_filter']) if params['quantity_threshold_filter'].present?
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:product_id, :quantity, :color, :size, :weight, :price_cents, :sale_price_cents, :cost_cents, :sku, :length, :width, :height, :note)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.haml
= form_for @inventory do |f|
  - if @inventory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@inventory.errors.count, "error")} prohibited this inventory from being saved:"
      %ul
        - @inventory.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :product_id
    = f.text_field :product_id
  .field
    = f.label :quantity
    = f.text_field :quantity
  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :size
    = f.text_field :size
  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :price_cents
    = f.text_field :price_cents
  .field
    = f.label :sale_price_cents
    = f.text_field :sale_price_cents
  .field
    = f.label :cost_cents
    = f.text_field :cost_cents
  .field
    = f.label :sku
    = f.text_field :sku
  .field
    = f.label :length
    = f.text_field :length
  .field
    = f.label :width
    = f.text_field :width
  .field
    = f.label :height
    = f.text_field :height
  .field
    = f.label :note
    = f.text_field :note
  .actions
    = f.submit 'Save'

app/views/inventories/edit.html.haml
%h1 Editing inventory

= render 'form'

app/views/inventories/index.html.haml
%h1 Inventory

.filter
  = form_tag inventories_path, :method => :get do
    .ui.input
      = text_field_tag 'product_id_filter', nil, placeholder: 'Enter a Product ID'
    %br
    .ui.input
      = text_field_tag 'sku_filter', nil, placeholder: 'Enter a SKU'
    .u.input
      = number_field_tag 'quantity_threshold_filter', nil, placeholder: 0
    .ui.input
      = submit_tag 'Filter'
%br

.table-div{:style => 'overflow: scroll;'}
  %table.ui.celled.table
    %thead
      %tr
        %th Product
        %th Sku
        %th Quantity
        %th Color
        %th Size
        %th Price
        %th Cost

    %tbody
      - @inventories.each do |inventory|
        %tr
          %td= inventory.product.product_name
          %td= inventory.sku
          %td= inventory.quantity
          %td= inventory.color
          %td= inventory.size
          %td= inventory.price
          %td= inventory.cost
.sixteen.wide.column
  .ui.pagination.menu
    = will_paginate @products, :class => 'ui pagination menu'

app/views/inventories/new.html.haml
%h1 New inventory

= render 'form'

= link_to 'Back', inventories_path

app/views/inventories/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @inventory.product_id
%p
  %b Quantity:
  = @inventory.quantity
%p
  %b Color:
  = @inventory.color
%p
  %b Size:
  = @inventory.size
%p
  %b Weight:
  = @inventory.weight
%p
  %b Price cents:
  = @inventory.price_cents
%p
  %b Sale price cents:
  = @inventory.sale_price_cents
%p
  %b Cost cents:
  = @inventory.cost_cents
%p
  %b Sku:
  = @inventory.sku
%p
  %b Length:
  = @inventory.length
%p
  %b Width:
  = @inventory.width
%p
  %b Height:
  = @inventory.height
%p
  %b Note:
  = @inventory.note

= link_to 'Edit', edit_inventory_path(@inventory)
\|
= link_to 'Back', inventories_path