config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :inventories
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :inventory, :foreign_key => :id, :primary_key => :inventory_id
  has_one :product, :foreign_key => :id, :primary_key => :product_id
  monetize :total_cents
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /orders or /orders.json
  def index
    orders = current_user.orders
    orders = orders.joins(:inventory).where(:inventory => {:product_id => params['product_id_filter']}) if params['product_id_filter'].present?
    orders = orders.joins(:inventory).where(:inventory => {:sku => params['sku_filter']}) if params['sku_filter'].present?

    @orders = orders.paginate(page: params[:page], per_page: 10).order(:product_name)

    @avg_order_total = orders.map {|order| order.total.amount}.inject(&:+)
    @avg_order_total = 0 if @avg_order_total.blank?
    @avg_order_total = @avg_order_total / orders.size unless @avg_order_total == 0

    @total_order_count = orders.size

    @paid_count = orders.where(:order_status => 'Paid').size
    @open_count = orders.where(:order_status => 'Open').size
    @shipped_count = orders.where(:order_status => 'Shipped').size
    @fulfilled_count = orders.where(:order_status => 'Fulfulled').size
    @pending_count = orders.where(:order_status => 'Pending').size
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:product_id, :street_address, :apartment, :city, :state, :country_code, :zip, :phone_number, :email, :name, :order_status, :payment_ref, :transaction_id, :payment_amt_cents, :ship_charged_cents, :ship_cost_cents, :subtotal_cents, :total_cents, :shipper_name, :payment_date, :shipped_date, :tracking_number, :tax_total_cents)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :product_id
    = f.text_field :product_id
  .field
    = f.label :street_address
    = f.text_field :street_address
  .field
    = f.label :apartment
    = f.text_field :apartment
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :country_code
    = f.text_field :country_code
  .field
    = f.label :zip
    = f.text_field :zip
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :order_status
    = f.text_field :order_status
  .field
    = f.label :payment_ref
    = f.text_field :payment_ref
  .field
    = f.label :transaction_id
    = f.text_field :transaction_id
  .field
    = f.label :payment_amt_cents
    = f.text_field :payment_amt_cents
  .field
    = f.label :ship_charged_cents
    = f.text_field :ship_charged_cents
  .field
    = f.label :ship_cost_cents
    = f.text_field :ship_cost_cents
  .field
    = f.label :subtotal_cents
    = f.text_field :subtotal_cents
  .field
    = f.label :total_cents
    = f.text_field :total_cents
  .field
    = f.label :shipper_name
    = f.text_field :shipper_name
  .field
    = f.label :payment_date
    = f.datetime_select :payment_date
  .field
    = f.label :shipped_date
    = f.datetime_select :shipped_date
  .field
    = f.label :tracking_number
    = f.text_field :tracking_number
  .field
    = f.label :tax_total_cents
    = f.text_field :tax_total_cents
  .actions
    = f.submit 'Save'

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Orders
%strong= "Total Orders: #{@total_order_count}"
%br
%strong= "Average Sale Total:#{number_to_currency(@avg_order_total)}"


.filter
  = form_tag orders_path, :method => :get do
    .ui.input
      = text_field_tag 'product_id_filter', nil, placeholder: 'Enter a Product ID'
    %br
    .ui.input
      = text_field_tag 'sku_filter', nil, placeholder: 'Enter a SKU'
    %br
    .ui.input
      = submit_tag 'Filter'
%br

.table-div{:style => 'overflow: scroll;'}
  %table.ui.celled.table
    %thead
      %tr
        %th.sorted.ascending Name
        %th.sorted.ascending Email
        %th.sorted.ascending Product
        %th.sorted.ascending Color
        %th.sorted.ascending Size
        %th.sorted.ascending Order status
        %th.sorted.ascending Total
        %th.sorted.ascending Transaction
        %th.sorted.ascending Shipper name
        %th.sorted.ascending Tracking number
    %tbody
      - @orders.each do |order|
        %tr
          %td= order.name
          %td= order.email
          %td= order.product.product_name
          %td= order.inventory.color
          %td= order.inventory.size
          %td= order.order_status
          %td= order.total
          %td= order.transaction_id
          %td= order.shipper_name
          %td= order.tracking_number
  %br
  %strong="Paid Orders:#{@paid_count}"
  %br
  %strong="Open Orders:#{@open_count}"
  %br
  %strong="Shipped Orders:#{@shipped_count}"
  %br
  %strong="Fulfilled Orders:#{@fulfilled_count}"
  %br
  %strong="Pending Orders:#{@pending_count}"

  .ui.pagination.menu
    = will_paginate @orders, :class => 'ui pagination menu'
  

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @order.product_id
%p
  %b Street address:
  = @order.street_address
%p
  %b Apartment:
  = @order.apartment
%p
  %b City:
  = @order.city
%p
  %b State:
  = @order.state
%p
  %b Country code:
  = @order.country_code
%p
  %b Zip:
  = @order.zip
%p
  %b Phone number:
  = @order.phone_number
%p
  %b Email:
  = @order.email
%p
  %b Name:
  = @order.name
%p
  %b Order status:
  = @order.order_status
%p
  %b Payment ref:
  = @order.payment_ref
%p
  %b Transaction:
  = @order.transaction_id
%p
  %b Payment amt cents:
  = @order.payment_amt_cents
%p
  %b Ship charged cents:
  = @order.ship_charged_cents
%p
  %b Ship cost cents:
  = @order.ship_cost_cents
%p
  %b Subtotal cents:
  = @order.subtotal_cents
%p
  %b Total cents:
  = @order.total_cents
%p
  %b Shipper name:
  = @order.shipper_name
%p
  %b Payment date:
  = @order.payment_date
%p
  %b Shipped date:
  = @order.shipped_date
%p
  %b Tracking number:
  = @order.tracking_number
%p
  %b Tax total cents:
  = @order.tax_total_cents

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path